name: Master yml

on:
  workflow_dispatch:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Show github json
        if: github.event_name == 'pull_request' && !contains(github.head_ref, 'upgrade-dependencies-*')
        run: |
          echo $JSON