name: Slave yml

on:
  workflow_run:
    workflows: [Upgrade dependencies]
    types:
      - completed
    branches:
      - upgrade-dependencies-*

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Show github json
        run: |
          echo $JSON